// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCDK5sHrKgLP9obUDdP3P2iYI5vYcJXIY0',
    appId: '1:1048123089034:web:8be602b77f33f58093cd73',
    messagingSenderId: '1048123089034',
    projectId: 'chat-app-flutter-2d3b6',
    authDomain: 'chat-app-flutter-2d3b6.firebaseapp.com',
    storageBucket: 'chat-app-flutter-2d3b6.appspot.com',
    measurementId: 'G-WVJR30C5Y7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCwwO2xPidkL4pLfwE9QjPZNRYLzGd_xtQ',
    appId: '1:1048123089034:android:3c09c0266da300e193cd73',
    messagingSenderId: '1048123089034',
    projectId: 'chat-app-flutter-2d3b6',
    storageBucket: 'chat-app-flutter-2d3b6.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAlpUzPM_3aklgVoWml1Ss8nlgrJILoam4',
    appId: '1:1048123089034:ios:52dfcc32f421ec3a93cd73',
    messagingSenderId: '1048123089034',
    projectId: 'chat-app-flutter-2d3b6',
    storageBucket: 'chat-app-flutter-2d3b6.appspot.com',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAlpUzPM_3aklgVoWml1Ss8nlgrJILoam4',
    appId: '1:1048123089034:ios:52dfcc32f421ec3a93cd73',
    messagingSenderId: '1048123089034',
    projectId: 'chat-app-flutter-2d3b6',
    storageBucket: 'chat-app-flutter-2d3b6.appspot.com',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCDK5sHrKgLP9obUDdP3P2iYI5vYcJXIY0',
    appId: '1:1048123089034:web:1c6287b4492d115293cd73',
    messagingSenderId: '1048123089034',
    projectId: 'chat-app-flutter-2d3b6',
    authDomain: 'chat-app-flutter-2d3b6.firebaseapp.com',
    storageBucket: 'chat-app-flutter-2d3b6.appspot.com',
    measurementId: 'G-4K6YYZH10Z',
  );
}
